site_name: "100 Great Bitcoin Stack Exchange Questions"

theme:
  name: material
  
  icon:
    logo: material/bitcoin

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        # icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        # icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

# page tree
nav:
  - Home: index.md

  - Transactions:
    - "Q1": "transactions/q1.md"

  - Wallets:
    - "Q20": "wallets/q0.md"

  - Nodes:
    - "Q40": "nodes/q0.md"

  - Mining:
    - "Q50": "mining/q0.md"

  - Cryptography:
    - "Q70": "cryptography/q0.md"

  - History:
    - "Q90": "history/q0.md"
