site_name: "100 Great Bitcoin Stack Exchange Questions"

theme:
  name: material
  
  icon:
    logo: material/bitcoin

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        # icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        # icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

# page tree
nav:
  - Home: index.md

  - Transactions:
    - "Q1": "transactions/q1.md"

  - Wallets:
    - "Q21": "wallets/q21.md"
    - "Q22": "wallets/q22.md"

  - Nodes & P2P:
    - "Q41": "nodes-p2p/q41.md"

  - Mining:
    - "Q61": "mining/q0.md"

  - Cryptography:
    - "Q71": "cryptography/q0.md"

  - History:
    - "Q91": "history/q91.md"
